
name: Deploy frontend to GitHub Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install client dependencies
        run: |
          cd client
          npm ci
      - name: Build frontend
        run: |
          cd client
          npm run build
      - name: Setup dist directory structure
        run: |
          mkdir -p client/dist/images
          mkdir -p client/dist/publications
      - name: Copy all assets to dist
        run: |
          # Copy images from client/public/images
          if [ -d "client/public/images" ]; then
            cp -r client/public/images/* client/dist/images/
          fi
          # Copy images from root public/images  
          if [ -d "public/images" ]; then
            cp -r public/images/* client/dist/images/
          fi
          # Copy publications
          if [ -d "public/publications" ]; then
            cp -r public/publications/* client/dist/publications/
          fi
          # Copy PDF files from client/public
          if [ -f "client/public/Lebenslauf-Ayadi.pdf" ]; then
            cp client/public/*.pdf client/dist/
          fi
      - name: SPA 404 fallback
        run: cp "client/dist/index.html" "client/dist/404.html"
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: client/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
